gab: resolve assertion when traversing GAL
With -D_GLIBCXX_DEBUG set, observe in NSP:

```
f3  __GI_abort () at abort.c:73
f4  __gnu_debug::_Error_formatter::_M_error at ../../../../../libstdc++-v3/src/c++11/debug.cc:1320
f5  __gnu_debug::_Safe_iterator<…>::operator-> at /usr/include/c++/15/debug/safe_iterator.h:370
f6  [lambda] (i=END) at include/gromox/ab_tree.hpp:171
f11 std::visit at /usr/include/c++/15/variant:1954
f12 gromox::ab_tree::ab_base::iterator::iterator<> (i=END) at include/gromox/ab_tree.hpp:171
f13 gromox::ab_tree::ab_base::end at include/gromox/ab_tree.hpp:242
f14 nsp_interface_position_in_list at exch/nsp/nsp_interface.cpp:658
f15 nsp_interface_query_rows at exch/nsp/nsp_interface.cpp:820
```

observe in zcore:

```
/usr/include/c++/15/debug/safe_iterator.h:370:
In function:
    constexpr gnu_debug::_Safe_iterator<_Iterator, _Sequence,
    _Category>::pointer gnu_debug::_Safe_iterator<_Iterator, _Sequence,
    _Category>::operator->() const [with _Iterator = gnu_cxx::
    normal_iterator<const sql_user*, std::vector<sql_user,
    std::allocator<sql_user> > >; _Sequence = std::debug::vector<sql_user>;
    _Category = std::forward_iterator_tag; pointer = const sql_user*]
Error: attempt to dereference a past-the-end iterator.
Objects involved in the operation:
    iterator "this" @ 0x7bf9320998a8 {
      type = gnu_cxx::normal_iterator<sql_user const*, std::vector<sql_user, std::allocator<sql_user> > > (constant iterator);
      state = past-the-end;
      references sequence with type 'std::debug::vector<sql_user, std::allocator<sql_user> >' @ 0x7d19491f80a8
    }
Aborted
```

1. The iterator() constructor was called with `i=m_users.cend()`, but then evaluates
   expression `i->id`, which is not a valid thing to do for the end
   iterator.

2. operator== compared all members, which is wrong if `mid`

Fixes: gromox-2.40-22-gd4f1761ba
References: DESK-3151