build: resolve link failure on D12
ld: tools/event.o: undefined reference to symbol 'SSL_shutdown@@OPENSSL_3.0.0'
ld: /lib/x86_64-linux-gnu/libssl.so.3: error adding symbols: DSO missing from command line

qsock uses generic_connection (thus ~generic_connection thus
SSL_shutdown) since 7d5117962.

Fixes: gromox-2.30-40-g7d5117962