build: resolve build failures on i586
http_parser.cpp:109:29: error: conflicting declaration 'size_t g_rqbody_max_size'
ld: undefined reference to symbol '_ZN3fmt2v87vformatB5cxx11ENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_20basic_format_contextINS0_8appenderEcEEEE'
ld -o http: /usr/lib/x86_64-linux-gnu/libfmt.so.8: error adding symbols: DSO missing from command line

Fixes: gromox-2.13-23-gcb4cbada0