ldap_adaptor: resolve resource_pool race with double-free
Due to a missing lock, `g_conn_pool.clear()` can modify the pool (in
this instance, free it) while a `g_conn_pool.get_wait()` in another
thread obtains an object. The problem can trigger when
per-organization LDAP settings / multiple LDAP servers are used, as
that scenario needs to disable connection pooling.

Original report:

Dec 05 13:51:35 slcocp0001 http[26921]: double free or corruption (fasttop)
f0  raise (libc.so.6 + 0x4ad2b)
f1  abort (libc.so.6 + 0x4c3e5)
f2  __libc_message (libc.so.6 + 0x90c27)
f3  malloc_printerr (libc.so.6 + 0x98cca)
f4  _int_free (libc.so.6 + 0x9a8a4)
f5  BIO_free (libcrypto.so.1.1 + 0xdc768)
f6  BIO_free_all (libcrypto.so.1.1 + 0xdd4d4)
f7  SSL_free (libssl.so.1.1 + 0x457d3)
f8  n/a (libldap_r-2.4.so.2 + 0x3ceda)
f9  ber_sockbuf_remove_io (liblber-2.4.so.2 + 0x9edd)
f10 ber_int_sb_destroy (liblber-2.4.so.2 + 0xa6b2)
f11 ber_sockbuf_free (liblber-2.4.so.2 + 0xa72c)
f12 ldap_ld_free (libldap_r-2.4.so.2 + 0x1ea91)
f13 operator() (libgxs_ldap_adaptor.so + 0x1c2f)
f14 clear (libgxs_ldap_adaptor.so + 0x3951)
f15 login_gen (libgxs_authmgr.so + 0x290d)

ASAN report:

ERROR: AddressSanitizer: heap-use-after-free on address 0x6030001ca4b8
READ of size 8 at 0x6030001ca4b8 thread T71
f0 std::enable_if<std::__and_<std::__not_<std::__is_tuple_like<ldap*> >, std::is_move_constructible<ldap*>, std::is_move_assignable<ldap*> >::value, void>::type std::swap<ldap*>(ldap*&, ldap*&) /usr/include/c++/7/bits/move.h:198
f1 reset /usr/include/c++/7/bits/unique_ptr.h:369
f2 operator= /usr/include/c++/7/bits/unique_ptr.h:278
f3 gx_ldap_bind exch/ldap_adaptor.cpp:145
f4 ldaplogin_host exch/ldap_adaptor.cpp:221
f5 ldaplogin_dpool exch/ldap_adaptor.cpp:232
f6 ldap_adaptor_login3(char const*, char const*, sql_meta_result const&) exch/ldap_adaptor.cpp:239
f7 login_gen exch/authmgr.cpp:248

0x6030001ca4b8 is located 24 bytes inside of 32-byte region [0x6030001ca4a0,0x6030001ca4c0)
freed by thread T70 here:
f0 operator delete(void*) (/usr/lib64/libasan.so.4+0xde530)
f1 deallocate /usr/include/c++/7/ext/new_allocator.h:125
f2 deallocate /usr/include/c++/7/bits/alloc_traits.h:462
f3 _M_put_node /usr/include/c++/7/bits/stl_list.h:387
f4 _M_clear /usr/include/c++/7/bits/list.tcc:80
f5 clear /usr/include/c++/7/bits/stl_list.h:1406
f6 clear include/gromox/resource_pool.hpp:98
f7 ldap_adaptor_login3(char const*, char const*, sql_meta_result const&) exch/ldap_adaptor.cpp:247
f8 login_gen exch/authmgr.cpp:248

previously allocated by thread T71 here:
f0 operator new(unsigned long) (/usr/lib64/libasan.so.4+0xdd830)
f1 allocate /usr/include/c++/7/ext/new_allocator.h:111
f2 allocate /usr/include/c++/7/bits/alloc_traits.h:436
f3 _M_get_node /usr/include/c++/7/bits/stl_list.h:383
f4 _M_create_node<> /usr/include/c++/7/bits/stl_list.h:572
f5 _M_insert<> /usr/include/c++/7/bits/stl_list.h:1801
f6 emplace_back<> /usr/include/c++/7/bits/stl_list.h:1133
f7 get_wait<> include/gromox/resource_pool.hpp:75
f8 ldaplogin_dpool exch/ldap_adaptor.cpp:230
f9 ldap_adaptor_login3(char const*, char const*, sql_meta_result const&) exch/ldap_adaptor.cpp:239
f10 login_gen exch/authmgr.cpp:248

References: DESK-1490