build: resolve link failure for kdb2mt
/usr/bin/ld: tools/kdb2mt.o: undefined reference to symbol '_ZN4Json5ValueD1Ev'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libjsoncpp.so.24: error adding symbols: DSO missing from command line