Revert "build: resolve llvm18-libc++ compile error"
This reverts commit 873e897119ea4580e2cec326967177397aec4860.

It breaks compilation on gcc15 with -D_GLIBCXX_DEBUG.

```
/usr/include/c++/15/debug/helper_functions.h: In instantiation of 'constexpr bool __gnu_debug::__valid_range_aux(_InputIterator, _InputIterator, std::random_access_iterator_tag) [with _InputIterator = gromox::ab_tree::ab_base::iterator]':
/usr/include/c++/15/debug/helper_functions.h:201:44:   required from 'constexpr bool __gnu_debug::__valid_range_aux(_InputIterator, _InputIterator, std::__false_type) [with _InputIterator = gromox::ab_tree::ab_base::iterator]'
  201 |       return __gnu_debug::__valid_range_aux(__first, __last,
  202 |                                             std::__iterator_category(__first));
/usr/include/c++/15/debug/helper_functions.h:271:44:   required from 'constexpr bool __gnu_debug::__valid_range(_InputIterator, _InputIterator) [with _InputIterator = gromox::ab_tree::ab_base::iterator]'
  271 |       return __gnu_debug::__valid_range_aux(__first, __last, _Integral());
/usr/include/c++/15/bits/stl_algo.h:1971:7:   required from 'constexpr _FIter std::lower_bound(_FIter, _FIter, const _Tp&, _Compare) [with _FIter = gromox::ab_tree::ab_base::iterator; _Tp = char*; _Compare = nsp_interface_seek_entries(NSPI_HANDLE, uint32_t, STAT*, const PROPERTY_VALUE*, const MID_ARRAY*, const LPROPTAG_ARRAY*, NSP_ROWSET**)::<lambda(gromox::ab_tree::minid, const char*)>]'
 1971 |       __glibcxx_requires_partitioned_lower_pred(__first, __last,
nsp_interface.cpp:996:29:   required from here
  996 | auto it = std::lower_bound(pbase->ubegin(), pbase->uend(), ptarget->value.pstr,
  997 |                            [&](ab_tree::minid m1, const char *val)
  998 |                            { return strcasecmp(pbase->displayname(m1).c_str(), val) < 0; });
/usr/include/c++/15/debug/helper_functions.h:189:20: error: use of deleted function 'constexpr auto gromox::ab_tree::ab_base::iterator::operator<=>(const gromox::ab_tree::ab_base::iterator&) const'
  189 |         && __first <= __last;
In file included from exch/nsp/nsp_interface.cpp:23:
include/gromox/ab_tree.hpp:190:32: note: declared here
  190 |                 constexpr auto operator<=>(const iterator &other) const = delete;
/usr/include/c++/15/debug/helper_functions.h:189:20: note: use '-fdiagnostics-all-candidates' to display considered candidates
  189 |         && __first <= __last;
```