ews: avoid use of "timezone" variable
The "timezone" variable is specified by POSIX.1-2004, though FreeBSD
does not implement that part, and instead, "timezone" refers to some
historic C function by the same name.

	exch/ews/serialization.cpp:72:12: error: invalid operands to
	binary expression ('time_t' (aka 'long') and 'char *(int,
	int)')
	        timestamp -= timezone;

But mktime is not even needed, because we have gmtime.

See-also: gromox-1.26-67-ga67385c7a
See-also: gromox-2.20-99-g5278a988b