build: resolve build failure on Ubuntu 24
Cherry-pick commit 696a9885fa34eb79f118bc7a5f7b5bad99f7af68 .

exch/exmdb/common_util.cpp: In function '{anonymous}::GP_RESULT exmdb::gp_storeprop(uint32_t, TAGGED_PROPVAL&, sqlite3*)':
exch/exmdb/common_util.cpp:1724:25: error: ambiguous overload for 'operator!=' (operand types are 'ec_error_t' and 'int')
 1724 |   if (err != 0)