build: Debian ld build fixes
/usr/bin/x86_64-linux-gnux32-ld.bfd: tests/oxcmail_ie.o: undefined reference to symbol '_ZNK5vmime4body12getPartCountEv'
/usr/bin/x86_64-linux-gnux32-ld.bfd: /usr/lib/x86_64-linux-gnux32/libwmime.so.2: error adding symbols: DSO missing from command line