all: add missing parameter list to C function declarations
In C, f() means that arguments are unspecified, but for 0 arguments,
f(void) is needed.

Once done, 2 instances of coding error become apparent:

MTA_SYSTEM/mpc_plugins/mail_forwarder/mail_forwarder.c:318:3: error: too many
arguments to function ‘mail_forwarder_free’