build: resolve D12 link failure
tools/edb_pack.o: undefined reference to symbol '_ZN8EXT_PULL8g_uint16EPt'
ld: libgromox_common.so.0: error adding symbols: DSO missing from command line