all: fix 1010 instances of implicit declarations
e.g. conflict with built-in functions:
SYSTEM_ADMIN/admin_log/main/main.c:26:3:
warning: implicit declaration of function "exit" [-Wimplicit-function-declaration]
warning: incompatible implicit declaration of built-in function "exit"

e.g. totally undeclared:
EXCHANGE_SYSTEM/service_plugins/str_table/main.c:49:18:
warning: implicit declaration of function "atoi" [-Wimplicit-function-declaration]

e.g. misspellings:
EXCHANGE_SYSTEM/hpm_plugins/mod_proxy/main.c:116:5:
warning: implicit declaration of function "print";
did you mean "printf"? [-Wimplicit-function-declaration]