mapi_lib: resolve an OOB read within lookup_font
`{\rtf1\f-8 foo}` causes:

```
ERROR: AddressSanitizer: global-buffer-overflow on address
READ of size 8 at %ptr thread T0
    f0 std::string::_M_data() const
    f1 std::string::c_str() const
    f2 cmd_f lib/mapi/rtf.cpp:2008
    f3 convert_group_node lib/mapi/rtf.cpp:3386
    f4 convert_group_node lib/mapi/rtf.cpp:3418
    f5 rtf_to_html_boring lib/mapi/rtf.cpp:3482
    f6 rtf_to_html lib/mapi/rtf.cpp:3520
    f7 do_process_2 tools/ddbg.cpp:594
    f8 do_process_1 tools/ddbg.cpp:638
    f9 main tools/ddbg.cpp:661

%ptr is located 0 bytes after global variable 'fake_entries' defined
in 'lib/mapi/rtf.cpp:708:25' of size 448

%ptr is located 32 bytes before global variable 'guard variable for
(anonymous namespace)::rtf_reader::lookup_font(int)
const::fake_entries' defined in 'lib/mapi/rtf.cpp:708:25' of size 8
```

References: GXL-503