build: resolve FTBFS when GLIBCXX_DEBUG is set
exch/ews/structures.cpp: In member function 'const TAGGED_PROPVAL*
gromox::EWS::Structures::sShape::writes(uint32_t) const':
exch/ews/structures.cpp:897:34: error: operands to '?:' have different
types '__gnu_cxx::__normal_iterator<const TAGGED_PROPVAL*,
std::__cxx1998::vector<TAGGED_PROPVAL,
std::allocator<TAGGED_PROPVAL>>>' and 'std::nullptr_t'