delivery: resolve compile error on Alpine Linux/musl
musl/g++ is missing const char *strrchr(const char *); add a workaround.

mda/delivery_app/transporter.cpp: In function 'int transporter_unload_library(const char*)':
mda/delivery_app/transporter.cpp:702:23: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
  702 |                 ptr = path;