mapi_lib: add duration_cast for NT-to-system time conversions
clang libc++ defines system_clock as only having microsecond
granularity (unusual because systems like OpeBSD do know nanosecond
clocks), and the loss of precision in converting from 100ns-granular
durations to gromox::time_point requires an explicit conversion.

lib/mapi/rop_util.cpp:199:9: error: no viable conversion from returned value of type 'typename enable_if<__is_duration<duration<long long, ratio<1, 1000000>>>::value, duration<long long, ratio<1, 1000000>>>::type' (aka 'std::chrono::duration<long long, std::ratio<1, 1000000>>') to function return type 'gromox::time_point' (aka 'time_point<std::chrono::system_clock>')
        return std::chrono::duration_cast<gromox::time_point::duration>(nt_dur(nt_time) - nt_offset);