build: add libgromox_mapi to pffimport link
On DSO-strict link systems:

[  576s] libtool: link: g++ -Wall -Wmissing-declarations -std=c++17 -fvisibility=hidden -fvisibility-inlines-hidden -g -O2 -fdebug-prefix-map=/usr>
[  576s] /usr/bin/ld: tools/pffimport.o: undefined reference to symbol '_Z26tpropval_array_set_propvalP14TPROPVAL_ARRAYPK14TAGGED_PROPVAL'
[  576s] /usr/bin/ld: /usr/src/packages/BUILD/.libs/libgromox_mapi.so.0: error adding symbols: DSO missing from command line