codepage_lj: add missing <sstream> for istringstream
g++-7 reported

exch/codepage_lj.cpp:72:27: error: variable ‘std::istringstream ss’ has initializer but incomplete type