lib: disable STATIC_IN_CXX23 before g++-16
g++-13/14/15 have a bug wherein

.. code-block:: c++

	void f(auto &&){}
	int main() {
		f([]() static { });
		f([]() { });
	}

Does not compile:

error: mangling of ‘void f(auto:1&&) [with auto:1 = main()::<lambda()>]’ as
‘_Z1fIZ4mainEUlvE_EvOT_’ conflicts with a previous mangle
    1 |         void f(auto &&){}
note: previous mangling ‘void f(auto:1&&) [with auto:1 = main()::<lambda()>]’