build: resolve Debian ld failing
/usr/bin/x86_64-linux-gnu-ld.bfd: tools/exporter.o: undefined reference to symbol '_ZN5vmime7messageC1Ev'
/usr/bin/x86_64-linux-gnu-ld.bfd: /usr/local/lib/libwmime.so.2: error adding symbols: DSO missing from command line